name: Generate and Upload Coverage

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string
        default: 5.0.x
    secrets:
      codacy_api_token:
        required: true
        
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore
      
    - name: Cover
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage --no-restore
      
    - name: Populate Reports Variable
      shell: pwsh
      run: |
        $ReportPaths = Get-ChildItem *cobertura.xml -Recurse | Resolve-Path -Relative | Join-String -Separator ","
        echo "COVERAGE_REPORTS=$ReportPaths" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'CoverageReports'
      
    - name: Upload Coverage Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CoverageReports
        path: CoverageReports
        
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        api-token: ${{ secrets.codacy_api_token }}
        coverage-reports: '$($Env:COVERAGE_REPORTS)'
