on:
  workflow_dispatch:
        
jobs:
  call-workflow:
    uses: .github/workflows/test-reusable-workflow.yml@main
    with:
      username: Bert
    secrets:
      SECRET_TF_OPTIONS_PLAN: -var "beep=${{secrets.NOT_A_SECRET}}"
