on:
  workflow_dispatch:

env:
  TOTALLY_SECRET: ${{secrets.NOT_A_SECRET}}

jobs:
  call-workflow:
    uses: bortington/github-common/.github/workflows/test-reusable-workflow.yml@main
    with:
      tf_options_plan: -var-file test.tfvars
