on:
  workflow_dispatch:

env:
  TOTALLY_SECRET: ${{secrets.NOT_A_SECRET}}

jobs:
  call-workflow:
    uses: bortington/github-common/.github/workflows/test-reusable-workflow.yml@main
    with:
      username: Bert
    secrets:
      SECRET_TF_OPTIONS_PLAN: -var "beep=abc"
      SECRET_ENV: |
        TF_VAR_blah=${{secrets.NOT_A_SECRET}}
        TF_VAR_test2=${{secrets.NOT_A_SECRET}}
        TF_VAR_anotherthing=${{secrets.NOT_A_SECRET}}=12839u1d
