on:
  workflow_dispatch:

env:
  TOTALLY_SECRET: ${{secrets.NOT_A_SECRET}}

jobs:
  call-workflow:
    uses: bortington/github-common/.github/workflows/test-reusable-workflow.yml@main
    with:
      username: Bert
      env: TF_VAR_blah=${{env.TOTALLY_SECRET}}
    secrets:
      SECRET_TF_OPTIONS_PLAN: -var "beep=${{secrets.NOT_A_SECRET}}"
