on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: bortington/github-common/.github/workflows/test-reusable-workflow.yml@main
    with:
      tf_options_plan: -var-file test.tfvars
      test_pwsh: |
        $value = $env:super_secret
        Write-Output $env:super_secret
        Write-Output $value.Length
    secrets: 
      SECRET_ENV: |
        TF_VAR_codacy_api_token=${{secrets.CODACY_API_TOKEN}}
        TF_VAR_another_api_token=${{secrets.SECRET1}}
        TF_VAR_third_api_token=${{secrets.SECRET2}}
        TF_VAR_fourth_api_token=${{secrets.CODACY_API_TOKEN}}
