on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: bortington/github-common/.github/workflows/test-reusable-workflow.yml@main
    with:
      tf_options_plan: -var-file test.tfvars
      test_pwsh: |
        $value = $env:super_secret
        Write-Output $env:super_secret
        Write-Output $value.Length
    secrets: 
      SECRET_ENV: |
        super_secret=${{secrets.NOT_A_SECRET}}
