on:
  workflow_dispatch:
        
jobs:
  setup-env-vars:
    name: Setup Dynamic Terraform Variables
    runs-on: ubuntu-latest
    outputs:
      tf-args: ${{ steps.tf-args-step.outputs.tf-args }}
    steps:
      - name: Create Outputs
        id: tf-args-step
        run: |
          b64secret=`echo -n ${{ secrets.NOT_A_SECRET }} | base64`
          # echo "::add-mask::$b64secret"
          
          echo "tf-args=$b64secret" >> $GITHUB_OUTPUT
          
  call-workflow:
    needs: [setup-env-vars]
    uses: bortington/github-common/.github/workflows/test-reusable-workflow.yml@main
    with:
      username: ${{needs.setup-env-vars.outputs.tf-args}}
