on:
  workflow_dispatch:
        
jobs:
  setup-env-vars:
    name: Setup Dynamic Terraform Variables
    runs-on: ubuntu-latest
    outputs:
      tf-args: ${{ steps.tf-args-step.outputs.tf-args }}
    steps:
      - name: Create Outputs
        id: tf-args-step
        run: |    
          echo 'tf-args=${{ secrets.not_a_secret }}' >> $GITHUB_OUTPUT
          
  call-workflow:
    needs: [setup-env-vars]
    uses: bortington/github-common/.github/workflows/test-workflow.yml@main
    with:
      fred: ${{needs.setup-env-vars.outputs.tf-args}}
