on:
  workflow_call:
    inputs:
      environment:
        default: ''
        type: string
        required: false
        
      tf_plan_args:
        type: string
        default: ''
        required: false

      tf_var_keyvault_name:
        type: string
        default: ''
        required: false

      tf_var_keyvault_secrets:
        type: string
        default: ''
        required: false
        
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      OPTIONAL_SECRET:
        required: false
  
jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    permissions: 
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Azure Login
        uses: azure/login@v1
        env:
          ARM_USE_OIDC: true
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - uses: bortington/github-common/actions/terraform-keyvault-vars@main
        if: inputs.tf_var_keyvault_name != ''
        with:
          vault-name: ${{inputs.tf_var_keyvault_name}}
          secrets: ${{inputs.tf_var_keyvault_secrets}}
          
      - shell: pwsh
        run: |
          $opt = "${{secrets.OPTIONAL_SECRET != '' && secrets.OPTIONAL_SECRET || 'no value'}}"
          $opt2 = "${{secrets.OPTIONAL_SECRET}}"
          Write-Output $opt2.Length
          Write-Output "Beep: $opt"
          
      - run: |        
          echo "Test blah: ${TF_VAR_blah} ${{inputs.tf_plan_args}}"
