on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      env:
        description: Environment variables in key=value pairs. Can be used to pass secrets that aren't officially supported yet as environment variables
        type: string  # pass in string in export shell format eg. MYVAR=myvalue MYVAR2=myvalue2
        default: ''
        required: false
        
    secrets:
      SECRET_TF_OPTIONS_PLAN:
        description: "Optional tf args for the tf plan that may contains secrest"
        required: false
      SECRET_TF_OPTIONS_APPLY:
        description: "Optional tf args for the tf apply that may contains secrest"
        required: false
      SECRET_ENV:
        description: Environment variable in key=value pairs and newline separated. Can be used to pass secrets into environment variables
        required: false

env:
  ENV: ${{ inputs.env }}
  
jobs:
  blah:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment variables
        run: |
          echo "${{ env.ENV }}" >> "$GITHUB_ENV"
          
      - name: Setup secret environment variables
        shell: pwsh
        run: |
          $secretEnv = @"
          ${{secrets.SECRET_ENV}}
          "@

          foreach($line in $secretEnv)
          {
              if([string]::IsNullOrEmpty($line))
              {
                  continue
              }

              $key,$value = $line -split '=',2

              if($key -and $value)
              {
                  Write-Output "Adding secret environment variable $key"
                  Write-Output "::add-mask::$value"
                  Write-Output "$key=$value" >> $env:GITHUB_ENV
                  Write-Host "Testing: Added and masked secret env var $key. Value is $value"
              }
          }
          
      - name: Environment
        run: env | sort
      - run: |        
          echo "Hello ${{inputs.username}} ${{secrets.SECRET_TF_OPTIONS_PLAN}}"
          echo "Test thing: ${TF_VAR_blah}"
