on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
        
    secrets:
      SECRET_TF_OPTIONS_PLAN:
        description: "Optional tf args for the tf plan that may contains secrest"
        required: false
      SECRET_TF_OPTIONS_APPLY:
        description: "Optional tf args for the tf apply that may contains secrest"
        required: false

jobs:
  blah:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |        
        echo "Hello ${{inputs.username}} ${{secrets.SECRET_TF_OPTIONS_PLAN}}"
