name: Automatically increment workflow tags1

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**/*.yml'

jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: windows-latest
    outputs:
      files: ${{ steps.changes.outputs.files }}
      matrix-include: ${{ steps.changes.outputs.matrix-include }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Get changed files
        id: changes
        shell: pwsh
        run: |
          $changedWorkflows = (git diff HEAD^ HEAD --name-only  | Select-String -Pattern .github/workflows/.*\.yml | Select -Expand Matches | Select -Expand Value)
          $changes = @()

          foreach ($fileName in $changedWorkflows) 
          {
              if(Test-Path $fileName)
              {
                $file = Get-Item $fileName
            
                $changes += @{
                    file = $fileName
                    tagName = $file.BaseName
                }
              }
          }

          # Composite actions use the action.yml file name so we have to treat them separately and use the parent folder name.
          $changedActions = (git diff HEAD^ HEAD --name-only  | Select-String -Pattern actions/.*\.yml | Select -Expand Matches | Select -Expand Value)

          foreach ($fileName in $changedActions) 
          {
            if(Test-Path $fileName)
            {
              $file = Get-Item $fileName
              $file.DirectoryName

              $changes += @{
                  file = $file.Directory.BaseName
                  tagName = $file.Directory.BaseName
              }
            }
          }

          echo "::set-output name=matrix-include::$(ConvertTo-Json $changes -Compress)"
                
  update-tag:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix-include) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - run: echo ${{ matrix.file }}
      
      - run: echo ${{ matrix.tagName }}
      
      - name: Generate Version
        id: versioning
        uses: paulhatch/semantic-version@v4.0.3
        with:
          short_tags: false          
          tag_prefix: '${{ matrix.tagName }}/v'
          bump_each_commit: true
          
      - name: Tag Release
        run: |
          # git tag -a ${{ steps.versioning.outputs.version }}version_tag
          echo "version ${{ steps.versioning.outputs.version }}" 
          echo "version_tag ${{ steps.versioning.outputs.version_tag }}" 
          echo "authors  ${{ steps.versioning.outputs.authors }}" 
          # git push --tags
          # echo "Pushed tag v${{ steps.versioning.outputs.version }} to origin" 
        shell: bash
