name: Automatically increment workflow tags

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**/*.yml'

jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: windows-latest
    outputs:
      files: ${{ steps.changes.outputs.files }}
      matrix-include: ${{ steps.changes.outputs.matrix-include }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Get changed files
        id: changes
        shell: pwsh
        run: |
          $commandOutput = (git diff HEAD^ HEAD --name-only  | Select-String -Pattern .*\.yml | Select -Expand Matches | Select -Expand Value) 
          $changes = @()
          $files = @()
          
          foreach ($fileName in $commandOutput) {
              $file = Get-Item $fileName
              $changes += @{
                  file = $fileName
                  tagName = $file.BaseName
              }
          }
          
          $matrix = @{include=$changes}
          
          echo "::set-output name=files::$(ConvertTo-Json $files -Compress)"
          echo "::set-output name=matrix-include::$(ConvertTo-Json $changes -Compress)"
                
  update-tag:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix-include) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.file }}
      - run: echo ${{ matrix.tagName }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}
          dry_run: false
          default_bump: major
          create_annotated_tag: true
          tag_prefix: '${{ matrix.tagName }}/v'
